version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: f1_adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=f1_mysql
      - ADMINER_DESIGN=pepa-linha
    restart: unless-stopped
    networks:
      - f1-network

networks:
  f1-network:
    name: f1-network
    external: true 